teknologi-umum/bot

src/services/meme.js
=> feat(jokes): implementasi #2

package-lock.json, src/services/meme.js
=> Revert "Perbaikan #9"

src/services/covid/country.template.hbs, src/services/covid/global.template.hbs, src/services/covid/index.js, src/services/covid/utils.js, src/services/help.js, src/services/meme.js, src/services/quote.js, src/services/quote/index.js, test.js
`/covid` works but `/covid@BotName` doesn't work. This PR fixes that.
Plus some other housework.
=> `/covid` command fix + housework

src/app.js, src/services/bliding-ej.js
biar ga pusing ngejelasin kalo ada orang nanya
=> `/blidingej` command

package-lock.json, package.json, tests/covid.test.js, tests/eval.test.js
cc @ronnygunawan 
script usage:
```bash
$ npm run test
```
uvu documentation: https://github.com/lukeed/uvu/tree/master/docs
=> Setup unit test

src/app.js, src/services/blog.js
Cachenya belum ku bikin baru ngambil API saja
implements #19
=> implements #19

src/services/blog.js
Bug reason : url apis not encoded when get fired.
=> Fix devred 

src/services/blog/utils.js
close #30
perlu dishuffle dulu ngga sih?
=> fix: prevent undefined/null items in the array

CONTRIBUTING.md, README.md
added CONTRIBUTING.md
please check if it's beginner-friendly or not, if it is, you can merge it :)
=> docs: contributing

package-lock.json, src/services/bliding-ej.js, src/services/blog/blog.js, src/services/covid/index.js, src/services/eval/index.js, src/utils/command.js, tests/command.test.js
close #26
sebenernya mau ngerjain fitur yg scraping dari ddg, tapi sekalian bikin ini dulu biar gampang dapetin querynya
btw, ini kenapa package-lock.json nya jadi punya field integrity?
=> feat: add helper to get command argument

src/app.js, src/services/search.js, src/services/search/search.js, src/services/search/search.template.hbs, src/services/search/utils.js, src/services/snap/snap.js
close #35
abis PR ini dimerge aku mau ngerjain #39
note: ga ngerti kenapa itu 1 result bisa undefined
preview:
=> feat: add `/search` command

src/services/search/search.js
couldn't reproduce the ad results but it *should* work
=> feat: blocc dem ads

src/services/search/filter.js, src/services/search/search.js, src/services/search/search.template.hbs
=> feat: text preview

src/services/eval/parser.js, tests/eval.test.js
=> `/eval`: Support serializing BigInt

src/services/laodeai/handlers/stackoverflow.js, src/utils/sanitize.js, tests/laodeai.test.js, tests/laodeai_fixture/stackoverflow_next.html
just a bit of nitpick fixing these:
into these:
=> fix: parsing issue on laodeai

src/services/laodeai/index.js
=> fix: handle duckduckgo no result

src/services/quiz/index.js
tbh with you, I don't know what's wrong with this on the code side. guess I'll just sanitize it then
=> fix: sanitizing quiz messages

jsconfig.json, package-lock.json, package.json, src/app.js, src/services/analytics/index.js, src/services/bliding-ej/index.js, src/services/blog/index.js, src/services/blog/request.js, src/services/covid/index.js, src/services/dukun/index.js, src/services/eval/index.js, src/services/help/index.js, src/services/laodeai/index.js, src/services/meme/index.js, src/services/pastebin/index.js, src/services/poll/index.js, src/services/quiz/index.js, src/services/quote/index.js, src/services/search/index.js, src/services/snap/index.js, src/services/snap/utils.js, src/utils/logtail.js
Forget Loggly, now I'm going to use Logtail instead. Much cleaner, better design.
closes #99
=> feat: added logtail as a log management service

src/services/laodeai/index.js, src/services/search/index.js, src/utils/trimHtml.js
=> fix: properly trim HTML length

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/config.yml, README.md, README_id.md
hi!
added a few documentation patch for hacktoberfest newcomers
thanks
=> docs: updated for hacktoberfest

src/utils/trimHtml.js
=> fix: parse entity due to miscalculation

src/utils/sanitize.js, tests/laodeai_snapshot/stackoverflow_next, tests/laodeai_snapshot/stackoverflow_text
This fixes issue #107 
I have added the `.trim()` function at the end of the `sanitize` method. Is this OK?
=> Trim content

src/services/dukun/dukun.template.hbs
Hello and thank you for your interest on submitting a PR to this repository!
First and foremost, I hope you have read the CONTRIBUTING.md file.
If not, you can find it here: https://github.com/teknologi-umum/bot/blob/master/CONTRIBUTING.md
I would let you know that if you submit a PR without opening up an issue first,
your PR might be very likely rejected by the maintainers.
If you think you can go ahead without opening up an issue, please explain changes about your PR
in as much detail as possible.
Here is a few checklist that act as a reminder for your PR:
After everything's complete, you can delete this placeholder text. Again, thank you!
=> feat(dukun): replace dot with number.

src/services/meme/index.js
solved unhandled exception on jokesbapak2 error
=> fix: trycatch on jokes error

src/app.js, src/services/search/filter.js, src/services/search/index.js
closes #135 
the entry description wasn't sanitized before.
also added prevention for this case:
=> fix: even safer search

package-lock.json, package.json, src/app.js
per this issue https://github.com/telegraf/telegraf/issues/1372
by using this https://github.com/KnightNiwrem/telegraf-throttler
I'm not using the default setting. I'm just preventing incoming spam. But this will introduce another error when HTTP call is done multiple times:
```
HTTPError: Response code 403 (Forbidden)
at Request.<anonymous> (/home/reinaldy/repository/teknologi-umum/bot/node_modules/got/dist/source/as-promise/index.js:117:42)
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
code: undefined,
timings: {
start: 1636701547141,
socket: 1636701547141,
lookup: 1636701547142,
connect: 1636701547167,
secureConnect: 1636701547186,
upload: 1636701547186,
response: 1636701547213,
end: 1636701547214,
error: undefined,
abort: undefined,
phases: {
wait: 0,
dns: 1, …
```
=> perf: fighting concurrency

package-lock.json, src/utils/command.js
i filtering all of these invisible character for preventing error while execute commands
| Decimal Code | Meaning |
| ----------- | -------- | 
| &amp;#8203;  | zero-width-space |
| &amp;#8204; | zero-width-non-joiner |
| &amp;#8206;  | left-to-right-mark |
| &amp;#8207;  | right-to-left-mark |
=> fix: filtering invisible space character on command

docker-compose.yml, package-lock.json, package.json, src/app.js, src/services/covid/index.js, src/services/devread/index.js, src/services/dukun/index.js, src/services/meme/index.js, src/services/poll/index.js, src/services/quiz/index.js, src/utils/redis.js
tested? of course not. docker desktop gw gamau nyala
=> feat: migrating from redis to in memory

package-lock.json, package.json, src/app.js, src/services/poll/index.js
=> fix: better caching than yesterday

src/services/dukun/index.js
untested because I don't know how to test it
=> fix(dukun): don't destructure the value

src/services/quiz/index.js
=> fix: invalid extension on import

src/services/dukun/index.js
=> fix(dukun): invalid data was passed to JSON.parse

src/services/dukun/index.js
=> fix: dukunMaster doesn't have a fallback value

src/services/search/index.js
=> fix(search): handle `no results` from duckduckgo

src/services/poll/index.js
=> fix: remove cache for poll, just read directly from the database

src/services/meme/index.js
=> feat: enable jokesbapak2 on home group

package-lock.json, package.json, src/app.js, src/services/qr/index.js
=> feat: new command for generate qr code using /qr <url>

src/services/snap/index.js
- Remove mention from snap message
- Reply to snap command message instead of the snapped message
=> feat: remove mention from snap command

src/services/devread/index.js
Ngefix devread service caching
=> fix: caching

src/app.js, src/services/meme/index.js, src/services/qr/index.js, src/services/snap/index.js, src/services/snap/utils.js
- hardcoded dns resolvers
- properly log timeout error to sentry, with additional breadcrumbs for debugging
- use http2 with got
=> fix: handle timeout error

.github/workflows/ci.yml, Dockerfile, src/app.js
After this PR, I'll set up the required settings and configuration to be set on our VM.
Then, we can migrate the bot from fly.io to our own VM.
=> build: create docker image

src/utils/command.js, tests/command.test.js
=> fix: should respect new lines

src/services/pesto/index.js
Fixes https://teknologi-umum.sentry.io/share/issue/ed0bb32b20ce4daa84313fa7d2139baf/
=> fix: encode pesto response

src/services/meme/index.js, src/utils/home.js
All meme commands are not working.
the issue's here https://github.com/teknologi-umum/bot/issues/196#issue-1910219513
=> `/joke` set minimum user in a group

src/services/eval/currency.js
Depends on container deployment. See https://github.com/teknologi-umum/infrastructure/pull/1
=> fix(eval): use teknologi umum gold for currency api

src/services/dukun/index.js
Some people are still using suhu instead of dukun, so hope that this would solve the problem
=> feat: make suhu alias to dukun

src/services/pesto/index.js
Hello and thank you for your interest on submitting a PR to this repository!
First and foremost, I hope you have read the CONTRIBUTING.md file.
If not, you can find it here: https://github.com/teknologi-umum/bot/blob/master/CONTRIBUTING.md
I would let you know that if you submit a PR without opening up an issue first,
your PR might be very likely rejected by the maintainers.
If you think you can go ahead without opening up an issue, please explain changes about your PR
in as much detail as possible.
Here is a few checklist that act as a reminder for your PR:
After everything's complete, you can delete this placeholder text. Again, thank you!
=> feat: support bot command execution tengo code

src/app.js
Hello and thank you for your interest on submitting a PR to this repository!
First and foremost, I hope you have read the CONTRIBUTING.md file.
If not, you can find it here: https://github.com/teknologi-umum/bot/blob/master/CONTRIBUTING.md
I would let you know that if you submit a PR without opening up an issue first,
your PR might be very likely rejected by the maintainers.
If you think you can go ahead without opening up an issue, please explain changes about your PR
in as much detail as possible.
Here is a few checklist that act as a reminder for your PR:
After everything's complete, you can delete this placeholder text. Again, thank you!
=> feat: add tengo to valid commands

src/services/pesto/index.js
Hello and thank you for your interest on submitting a PR to this repository!
First and foremost, I hope you have read the CONTRIBUTING.md file.
If not, you can find it here: https://github.com/teknologi-umum/bot/blob/master/CONTRIBUTING.md
I would let you know that if you submit a PR without opening up an issue first,
your PR might be very likely rejected by the maintainers.
If you think you can go ahead without opening up an issue, please explain changes about your PR
in as much detail as possible.
Here is a few checklist that act as a reminder for your PR:
After everything's complete, you can delete this placeholder text. Again, thank you!
=> fix: using Tengo as defined on pesto repository
